/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -3,
    maxZoom: 2,
    defaultZoom: 0,
    imageFormat: "webp",
    minRegionX: -17,
    minRegionZ: -39,
    maxRegionX: 0,
    maxRegionZ: 7,
    worldName: "Shattered World",
    background: "#000000",
    markers: new Array()
}
