/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -3,
    maxZoom: 2,
    defaultZoom: 0,
    imageFormat: "webp",
    minRegionX: -5,
    minRegionZ: -9,
    maxRegionX: 21,
    maxRegionZ: 17,
    worldName: "Shattered Realms",
    background: "#000000",
    markers: new Array()
}
