/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -3,
    maxZoom: 2,
    defaultZoom: 0,
    imageFormat: "webp",
    minRegionX: -22,
    minRegionZ: -32,
    maxRegionX: 47,
    maxRegionZ: 37,
    worldName: "Tales of Iteria",
    background: "#000000",
    markers: new Array()
}
