/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -3,
    maxZoom: 2,
    defaultZoom: 0,
    imageFormat: "webp",
    minRegionX: -1,
    minRegionZ: -1,
    maxRegionX: 0,
    maxRegionZ: 0,
    worldName: "Tales of Iteria_minecraft_ventevas_realm",
    background: "#000000",
    markers: new Array()
}
